# Generated by Django 2.0 on 2021-03-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Role', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('Phone', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Garbage_type', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Productname', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Quantity', models.CharField(max_length=5)),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=10)),
                ('Date_Time', models.DateTimeField()),
                ('Weight', models.IntegerField()),
                ('GC_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.GarbageCollector')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Role', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=12)),
                ('OTP', models.IntegerField(max_length=4)),
                ('is_verified', models.BooleanField()),
                ('is_created', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='gc',
            name='GC',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='recycler',
        ),
        migrations.AlterField(
            model_name='admin',
            name='Role',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='GC',
        ),
        migrations.DeleteModel(
            name='Recycler',
        ),
        migrations.AddField(
            model_name='user',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin'),
        ),
        migrations.AddField(
            model_name='request',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.User'),
        ),
        migrations.AddField(
            model_name='garbagecollector',
            name='GC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin'),
        ),
    ]
