# Generated by Django 2.0 on 2021-03-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_auto_20210317_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consumer',
            new_name='User',
        ),
    ]
