# Generated by Django 2.0 on 2021-03-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0006_auto_20210317_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
