# Generated by Django 2.0 on 2021-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0007_auto_20210317_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagecollector',
            name='Role',
            field=models.CharField(max_length=30),
        ),
    ]
