# Generated by Django 2.0 on 2021-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0008_auto_20210318_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagecollector',
            name='Role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(max_length=50),
        ),
    ]
