# Generated by Django 2.0 on 2021-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0009_auto_20210318_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Role',
            field=models.CharField(max_length=50),
        ),
    ]
