# Generated by Django 2.0 on 2021-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0010_auto_20210318_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagecollector',
            name='Location',
            field=models.CharField(default='location', max_length=15),
        ),
    ]
