# Generated by Django 2.0 on 2021-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0011_garbagecollector_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='Phone',
            field=models.CharField(default='phone', max_length=12),
        ),
    ]
