# Generated by Django 2.0 on 2021-03-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0012_auto_20210325_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Weight',
            new_name='Quantity',
        ),
        migrations.AddField(
            model_name='request',
            name='Garbage_Description',
            field=models.CharField(default='Garbage_Description', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='Garbage_Type',
            field=models.CharField(default='Garbage_Type', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='Phone',
            field=models.CharField(default='Phone', max_length=12),
        ),
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.CharField(default='Status', max_length=10),
        ),
    ]
