# Generated by Django 2.0 on 2021-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0013_auto_20210326_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Date_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
