# Generated by Django 2.0 on 2021-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0014_auto_20210326_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Garbage_Type',
            field=models.CharField(default='Garbage_Type', max_length=50),
        ),
    ]
