# Generated by Django 2.0 on 2021-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0015_auto_20210326_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Productname',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductType',
            field=models.CharField(default='type', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(default='description', max_length=50),
        ),
    ]
