# Generated by Django 2.0 on 2021-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0018_auto_20210326_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
