# Generated by Django 2.0 on 2021-03-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0021_auto_20210326_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='p',
        ),
    ]
