# Generated by Django 2.0 on 2021-03-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0022_auto_20210326_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p',
        ),
    ]
