# Generated by Django 2.0 on 2021-03-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0023_remove_product_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
    ]
