# Generated by Django 2.0 on 2021-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0024_auto_20210326_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagetype',
            name='Price',
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
