# Generated by Django 2.0 on 2021-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0026_product_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
