# Generated by Django 2.0 on 2021-03-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0027_auto_20210326_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default='name', max_length=30)),
                ('Description', models.CharField(default='description', max_length=50)),
                ('Date', models.DateField(null=True)),
                ('ProductType', models.CharField(default='type', max_length=30)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('p', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin')),
            ],
        ),
    ]
