# Generated by Django 2.0 on 2021-03-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0028_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p',
        ),
    ]
