# Generated by Django 2.0 on 2021-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0030_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
