# Generated by Django 2.0 on 2021-03-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0031_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=30)),
                ('Subject', models.EmailField(max_length=50)),
                ('Message', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.User')),
            ],
        ),
    ]
