# Generated by Django 2.0 on 2021-03-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0032_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='admin',
        ),
    ]
