# Generated by Django 2.0 on 2021-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0033_remove_message_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Date',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
