# Generated by Django 2.0 on 2021-03-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0034_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin'),
        ),
    ]
