# Generated by Django 3.1.7 on 2021-04-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0035_cart_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Address',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
