# Generated by Django 2.0 on 2021-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0036_request_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Garbage_Description',
            field=models.CharField(default='Garbage_Description', max_length=100),
        ),
    ]
