# Generated by Django 2.0 on 2021-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0037_auto_20210401_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
