# Generated by Django 2.0 on 2021-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0038_auto_20210401_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Date_Time',
            field=models.CharField(default='Empty', max_length=40),
        ),
    ]
