# Generated by Django 2.0 on 2021-04-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0040_auto_20210403_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Quantity', models.IntegerField(null=True)),
                ('Item_Type', models.CharField(default='Garbage_Type', max_length=50)),
                ('Item_Price', models.IntegerField(null=True)),
                ('Item_Description', models.CharField(default='Garbage_Description', max_length=100)),
                ('Date', models.CharField(default='Empty', max_length=40)),
                ('pay_status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='pay_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='garbageitem',
            name='req_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.Request'),
        ),
    ]
