# Generated by Django 2.0 on 2021-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0041_auto_20210403_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbageitem',
            name='pay_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
