# Generated by Django 2.0 on 2021-04-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0042_auto_20210403_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garbage.Admin'),
        ),
    ]
