# Generated by Django 2.0 on 2021-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0043_auto_20210403_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image_Name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
